spring:
 application:
  name: eureka-producer-feign

eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/

server:
 port: 9002









#server:
# port: 9000
#eureka:
# instance:
#  hostname: localhost
# client:
#  registerWithEureka: false
#  fetchRegistry: false
#  serviceUrl:
#   defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka-con/



