spring:
 application:
  name: eureka-consumer-feign-hystrix

eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/
   #defaultZone: http://localhost:7000/eureka/

server:
 port: 9003

feign:
 hystrix:
  enabled: true

 # 暴露endpoints，其中包含的敏感信息
 management:
  endpoints:
   web:
    exposure:
     include: hystrix.stream









#server:
# port: 9000
#eureka:
# instance:
#  hostname: localhost
# client:
#  registerWithEureka: false
#  fetchRegistry: false
#  serviceUrl:
#   defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka-con/



